[package]
name = "android-hf-tokenizers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hf_tokenizers_cpp"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
tokenizers = "0.15.2"
